### PR TITLE
feat: add authentication example

### LINKED ISSUE #1: Make a Spring Boot example app to demontrate the use of Casdoor-Java-SDK
https://github.com/casdoor/casdoor-java-sdk is basically usable after PR: https://github.com/casdoor/casdoor-java-sdk/pull/6 . We can make an example here to show how to use it.

At this early stage, we can directly use casdoor-java-sdk, but in future, we may change to use a stronger wrapper: https://github.com/casdoor/casdoor-spring-boot-starter

So here are two paths:

1. For now: casdoor-spring-boot-example --> casdoor-java-sdk
2. In future: casdoor-spring-boot-example --> casdoor-spring-boot-starter --> casdoor-java-sdk

### PR DESCRIPTION
**Pull request by seriouszyx**
Fix: https://github.com/casdoor/casdoor-spring-boot-example/issues/1

### CODE REVIEW

**Comment by hsluoyz** [comment]
@seriouszyx how to use it? It is already a web page?

**Comment by seriouszyx** [comment]
@hsluoyz Firstly, the Casdoor should be deployed. When accessing the root page, the interceptor will check your session. If not exist, it will redirect to the login page provided by Casdoor. After login, it will get the token and parse it with casdoor-java-sdk, then you can visit the root page. Here is a demo video.

https://user-images.githubusercontent.com/33992371/139822974-95303a07-bde1-4b34-8293-910c372a4ab2.mp4

**Comment by seriouszyx** [comment]
@hsluoyz I add the doc to explain how to use it. I'm not sure that this example adequately explains the usage of SDK. If there is something to add and improve, plz tell me.

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
